import { Product } from '@models/product.model';
export const MOCK_PRODUCTS: Product[] = [
  {
    id: '1',
    name: 'Cyberpunk 2077',
    price: 59.99,
    discount: 40,

    imgUrl: 'https://images.igdb.com/igdb/image/upload/t_screenshot_big/sc6kz2.png',
  },
  {
    id: '2',
    name: 'The Witcher 3: Wild Hunt',
    price: 49.99,
    imgUrl: 'https://images.igdb.com/igdb/image/upload/t_screenshot_big/scoh3r.png',
  },
  {
    id: '3',
    name: 'Half-Life',
    price: 9.99,
    discount: 50,
    isFeatured: true,
    imgUrl: 'https://images.igdb.com/igdb/image/upload/t_screenshot_big/sc6kzj.png',
  },
  {
    id: '4',
    name: 'Baldur’s Gate II: Shadows of Amn',
    price: 4.99,
    isOwned: true,
    imgUrl: 'https://images.igdb.com/igdb/image/upload/t_screenshot_big/sc6l4d.png',
  },
  {
    id: '5',
    name: 'Planescape: Torment',
    price: 6.99,
    discount: 30,
    imgUrl: 'https://images.igdb.com/igdb/image/upload/t_screenshot_big/sc6kyp.png',
  },
  {
    id: '6',
    name: 'DOOM (1993)',
    price: 2.99,
    imgUrl: 'https://images.igdb.com/igdb/image/upload/t_screenshot_big/sc6wxw.png',
  },
  {
    id: '7',
    name: 'Diablo II',
    price: 14.99,
    imgUrl: 'https://images.igdb.com/igdb/image/upload/t_screenshot_big/sc6kw7.png',
  },
  {
    id: '8',
    name: 'Quake',
    price: 4.99,
    discount: 50,
    imgUrl: 'https://images.igdb.com/igdb/image/upload/t_screenshot_big/sc7kmj.png',
  },
  {
    id: '9',
    name: 'Stardew Valley',
    price: 9.99,
    imgUrl: 'https://images.igdb.com/igdb/image/upload/t_screenshot_big/sc6kpe.png',
  },
  {
    id: '10',
    name: 'Hollow Knight',
    price: 14.99,
    discount: 50,
    imgUrl: 'https://images.igdb.com/igdb/image/upload/t_screenshot_big/sc6lq9.png',
  },
  {
    id: '11',
    name: 'Celeste',
    price: 19.99,
    isOwned: true,
    imgUrl: 'https://images.igdb.com/igdb/image/upload/t_screenshot_big/sc6kze.png',
  },
  {
    id: '12',
    name: 'Terraria',
    price: 9.99,
    imgUrl: 'https://images.igdb.com/igdb/image/upload/t_screenshot_big/sc6kz1.png',
  },
  {
    id: '13',
    name: 'Disco Elysium',
    price: 29.99,
    discount: 30,
    imgUrl: 'https://images.igdb.com/igdb/image/upload/t_screenshot_big/sc84n7.png',
  },
  {
    id: '14',
    name: 'Undertale',
    price: 7.99,
    imgUrl: 'https://images.igdb.com/igdb/image/upload/t_screenshot_big/sc7nrz.png',
  },
  {
    id: '15',
    name: 'The Elder Scrolls III: Morrowind',
    price: 6.99,
    imgUrl: 'https://images.igdb.com/igdb/image/upload/t_screenshot_big/sc7ncm.png',
  },
  {
    id: '16',
    name: 'Gothic II',
    price: 4.49,
    discount: 50,
    imgUrl: 'https://images.igdb.com/igdb/image/upload/t_screenshot_big/sc7mwv.png',
  },
  {
    id: '17',
    name: 'Return to Castle Wolfenstein',
    price: 5.99,
    imgUrl: 'https://images.igdb.com/igdb/image/upload/t_screenshot_big/sc6wq1.png',
  }
];
